### ISSUE TITLE
Doesn't return unknown answers.

### ISSUE THREAD

**Issue by kgsensei** [kaedenbrinkman/goformative#1]
This is a really cool project idea.
Only issue, It doesn't return unknown answers. It only tells answers already submitted.
If there is a reasonable way to fix this, could you? Thanks.

**Comment by kaedenbrinkman** [comment]
I don't believe it's possible to access unknown answers through their API unless they've already been released. The API essentially gives just all the same information you can already see on the web interface :(

**Comment by kgsensei** [comment]
Ok, Thanks.
Do you think it would be possible to connect it to a database or look up answers and recommend one answer?
For multiple choice questions ofc.
